### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by MidimasterSoft** [markcwm/openb3dmax.help#2]
I tried to start this example: 
**openb3d.docs/extended/stencil_shadows2.bmx** 

but on BlitzMax NG there is an error message:

> Compile Error: Unable to find overload for positionentity(TLight,Double,Int,Int). Argument #2 is "Double" but declaration is "Float". 
> [C:/BasicNG/Spiegel/stencil_shadows2.bmx;45;0]
> Build Error: failed to compile (-1) C:/BasicNG/Spiegel/stencil_shadows2.bmx
> Process complete

The same problem in
 **openb3d.docs/extended/stencil_shadows_demo.bmx** 

additional here I cannot see a "zombie", but a strange looking object

The Double<-->Float problem exists in all examples where you call the RND() function. BlitzMax-NG returns a DOUBLE, but OpenB3D expects a FLOAT

**Comment by markcwm** [comment]
The zombie distortion means you need to update to the latest commit, that's a mistake I made when updating the Quat code, it messed up animation so I've reverted it.

You can just skip past that error message by using the -w overload warnings on option. So both examples work fine here.

**Comment by MidimasterSoft** [comment]
thanks, works now
